### PR TITLE
2.0.0

### PR DESCRIPTION
**Pull request by Sparksx**

### CODE REVIEW

**Comment by mathieugerard** [comment]
- [ ] Direction option should center the map
- [ ] Direction option should only be used once
- [ ] When in direction mode and the from is set, focus on the to field
- [ ] Add space between number and units in direction footer
- [ ] setSelected should center on place
- [ ] setUnit should not show the direction footer
- [ ] Add button in index.html to set user location
- [ ] Add alert when menu is clicked in index.html
- [ ] Add event when followUser button is clicked without location. Keep the button icon empty as long as there is no location.
- [ ] Display place details

**Comment by Sparksx** [comment]
- [ ] Fix local change
- [ ] Fix unit change

**Comment by mathieugerard** [comment]
Screen Shot 2019-11-08 at 4 01 49 PM

**Comment by mathieugerard** [comment]
Select place --> direction
Uncaught TypeError: Cannot read property 'footerManager' of undefined

**Comment by mathieugerard** [comment]
select place --> direction --> exit direction : the pin on the destination remains while the place is not selected.

**Comment by mathieugerard** [comment]
Enter direction --> click map from --> click map to --> exit directions : Uncaught (in promise)

**Comment by mathieugerard** [comment]
click twice on "go to direction mode" --> manager.ts:76 Uncaught (in promise)

**Comment by mathieugerard** [comment]
"select mapwize place" from outside venue does not center the map while "get selected place" returns the right place afterwards

**Comment by mathieugerard** [comment]
click "go to direction mode" while outside venue : Uncaught (in promise)

**Comment by mathieugerard** [comment]
Loader on floor selector is not taking main color into account

**Comment by mathieugerard** [comment]
Reversing the direction shows the search box for a fraction of second

**Comment by mathieugerard** [comment]
Bonus: if initialized with direction option, the zoom goes from world to venue to direction. Ideally the direction bounds should be displayed immediately, or at least the venue

**Comment by mathieugerard** [comment]
Screen Shot 2019-11-08 at 4 30 34 PM
Make it float on mobile

**Comment by mathieugerard** [comment]
Make sure it's aligned
Screen Shot 2019-11-08 at 4 33 37 PM

**Comment by mathieugerard** [comment]
On mobile, when place is selected the floor controller goes up but when the place is unselected it does not go down anymore

**Comment by mathieugerard** [comment]
Screen Shot 2019-11-08 at 4 37 21 PM
Floor selector bounds is too large and goes above the compass

**Comment by jaco3n4** [comment]
The field To do not empty when selecting a place => click on direction => click back to venue

**Pull request merged**
